title: Muhammad Zain Din
description: Red Team / Blue Team Showcase
baseurl: "" # Do not set unless using a subpath
url: "https://Cyber-Zain-Din.github.io"

remote_theme: jeffreytse/jekyll-theme-yat

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship

# Optional customizations
author:
  name: Muhammad Zain Din
  avatar: /assets/images/your-photo.jpg

yat:
  night_mode: "auto"
  sidebar:
    avatar: "/assets/images/avatar.png"
    bio: "Cybersecurity | SOC | Red Team & Blue Team Enthusiast"

markdown: kramdown
kramdown:
  input: GFM
